### ISSUE TITLE
TypeError when calling FocalLoss in "train_emotions_classifier.ipynb"

### ISSUE THREAD

**Issue by AssociationAssociation** [Knowledgator/LiqFit#2]
Thank you very much for providing LiqFit to the public and providing a chance to test your code. Unfortunately I fail at running the easiest example:

**When running notebook-example notebooks/train_emotions_classifier.ipynb in Google Colab (Python 3.10.12, T4) I get the following error:**

```
TypeError Traceback (most recent call last)
[<ipython-input-22-08f393ce2fbc>](https://localhost:8080/#) in <cell line: 6>()

4 backbone_model = AutoModelForSequenceClassification.from_pretrained('microsoft/deberta-v3-xsmall')
5 
----> 6 loss_func = FocalLoss(multi_target=True)
7 
8 model = LiqFitModel(backbone_model.config, backbone_model, loss_func=loss_func)

TypeError: FocalLoss.__init__() got an unexpected keyword argument 'multi_target'
```

While trying to fix, I compared the call to the class definition in script "losses.py", line 235, but can't resolve how boolean param "multi_target" would have to be passed to FocalLoss as it doesn't seem to accept it as also implied by the comment in lines 243-257:

```
Calculate focal loss while ignoring specified target labels.
        Args:
            logits (torch.Tensor): Model predictions.
            target (torch.Tensor): True labels.
            ignore_index (int): Label to ignore from loss calculation.
        alpha: Weighting factor that ranges between [0, 1]`.
            gamma: Focusing parameter gamma >= 0`.
            reduction (str | None): Reduction type for loss reduction.
                Supported: 'mean', 'sum' or 'none'. Defaults to 'mean'

        Returns:
            torch.Tensor: Loss tensor.
        Examples:
            loss = FocalLoss()(logits, targets)

```

How to fix?

Any help or directions for "self-help" would kindly be appreciated, thank you.

**Comment by Ingvarstep** [comment]
Thank you for raising the issue and sorry that you experienced this. 
Currently the `multi_target` parameter is redundant and **FocalLoss** shouldn't accept it, so you just need to remove it.

**Comment by AssociationAssociation** [comment]
thank you for your quick reply.

function call works fine with removed param, closing the issue as solved.

**Comment by Ingvarstep** [comment]
You are welcome!
